# coding: utf-8

"""
    DNS Configuration API

    The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.    # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bloxonednsconfig
from bloxonednsconfig.api.host_api import HostApi  # noqa: E501
from bloxonednsconfig.rest import ApiException


class TestHostApi(unittest.TestCase):
    """HostApi unit test stubs"""

    def setUp(self):
        self.api = bloxonednsconfig.api.host_api.HostApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_host_list(self):
        """Test case for host_list

        List DNS Host objects.  # noqa: E501
        """
        pass

    def test_host_read(self):
        """Test case for host_read

        Read the DNS Host object.  # noqa: E501
        """
        pass

    def test_host_update(self):
        """Test case for host_update

        Update the DNS Host object.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
