# coding: utf-8

"""
    DNS Configuration API

    The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.    # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bloxonednsconfig
from bloxonednsconfig.api.auth_nsg_api import AuthNsgApi  # noqa: E501
from bloxonednsconfig.rest import ApiException


class TestAuthNsgApi(unittest.TestCase):
    """AuthNsgApi unit test stubs"""

    def setUp(self):
        self.api = bloxonednsconfig.api.auth_nsg_api.AuthNsgApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_nsg_create(self):
        """Test case for auth_nsg_create

        Create the Auth NSG object.  # noqa: E501
        """
        pass

    def test_auth_nsg_delete(self):
        """Test case for auth_nsg_delete

        Delete the Auth NSG object.  # noqa: E501
        """
        pass

    def test_auth_nsg_list(self):
        """Test case for auth_nsg_list

        List Auth NSG objects.  # noqa: E501
        """
        pass

    def test_auth_nsg_read(self):
        """Test case for auth_nsg_read

        Read the Auth NSG object.  # noqa: E501
        """
        pass

    def test_auth_nsg_update(self):
        """Test case for auth_nsg_update

        Update the Auth NSG object.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
