# coding: utf-8

"""
    DNS Configuration API

    The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.    # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bloxonednsconfig
from bloxonednsconfig.models.inheritance2_inherited_bool import Inheritance2InheritedBool  # noqa: E501
from bloxonednsconfig.rest import ApiException


class TestInheritance2InheritedBool(unittest.TestCase):
    """Inheritance2InheritedBool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInheritance2InheritedBool(self):
        """Test Inheritance2InheritedBool"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bloxonednsconfig.models.inheritance2_inherited_bool.Inheritance2InheritedBool()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
