# coding: utf-8

"""
    DNS Configuration API

    The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.    # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bloxonednsconfig
from bloxonednsconfig.api.acl_api import AclApi  # noqa: E501
from bloxonednsconfig.rest import ApiException


class TestAclApi(unittest.TestCase):
    """AclApi unit test stubs"""

    def setUp(self):
        self.api = bloxonednsconfig.api.acl_api.AclApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_acl_create(self):
        """Test case for acl_create

        Create the ACL object.  # noqa: E501
        """
        pass

    def test_acl_delete(self):
        """Test case for acl_delete

        Delete the ACL object.  # noqa: E501
        """
        pass

    def test_acl_list(self):
        """Test case for acl_list

        List ACL objects.  # noqa: E501
        """
        pass

    def test_acl_read(self):
        """Test case for acl_read

        Read the ACL object.  # noqa: E501
        """
        pass

    def test_acl_update(self):
        """Test case for acl_update

        Update the ACL object.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
