# coding: utf-8

"""
    DNS Configuration API

    The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.    # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bloxonednsconfig
from bloxonednsconfig.api.forward_nsg_api import ForwardNsgApi  # noqa: E501
from bloxonednsconfig.rest import ApiException


class TestForwardNsgApi(unittest.TestCase):
    """ForwardNsgApi unit test stubs"""

    def setUp(self):
        self.api = bloxonednsconfig.api.forward_nsg_api.ForwardNsgApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_forward_nsg_create(self):
        """Test case for forward_nsg_create

        Create the Forward NSG object.  # noqa: E501
        """
        pass

    def test_forward_nsg_delete(self):
        """Test case for forward_nsg_delete

        Delete the Forward NSG object.  # noqa: E501
        """
        pass

    def test_forward_nsg_list(self):
        """Test case for forward_nsg_list

        List Forward NSG objects.  # noqa: E501
        """
        pass

    def test_forward_nsg_read(self):
        """Test case for forward_nsg_read

        Read the Forward NSG object.  # noqa: E501
        """
        pass

    def test_forward_nsg_update(self):
        """Test case for forward_nsg_update

        Update the Forward NSG object.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
