# coding: utf-8

"""
    DNS Configuration API

    The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.    # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bloxonednsconfig
from bloxonednsconfig.models.config_create_view_response import ConfigCreateViewResponse  # noqa: E501
from bloxonednsconfig.rest import ApiException


class TestConfigCreateViewResponse(unittest.TestCase):
    """ConfigCreateViewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigCreateViewResponse(self):
        """Test ConfigCreateViewResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bloxonednsconfig.models.config_create_view_response.ConfigCreateViewResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
