# coding: utf-8

"""
    DNS Configuration API

    The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.    # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConfigZoneAuthority(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'default_ttl': 'int',
        'expire': 'int',
        'negative_ttl': 'int',
        'protocol_rname': 'str',
        'refresh': 'int',
        'retry': 'int',
        'rname': 'str'
    }

    attribute_map = {
        'default_ttl': 'default_ttl',
        'expire': 'expire',
        'negative_ttl': 'negative_ttl',
        'protocol_rname': 'protocol_rname',
        'refresh': 'refresh',
        'retry': 'retry',
        'rname': 'rname'
    }

    def __init__(self, default_ttl=None, expire=None, negative_ttl=None, protocol_rname=None, refresh=None, retry=None, rname=None):  # noqa: E501
        """ConfigZoneAuthority - a model defined in Swagger"""  # noqa: E501

        self._default_ttl = None
        self._expire = None
        self._negative_ttl = None
        self._protocol_rname = None
        self._refresh = None
        self._retry = None
        self._rname = None
        self.discriminator = None

        if default_ttl is not None:
            self.default_ttl = default_ttl
        if expire is not None:
            self.expire = expire
        if negative_ttl is not None:
            self.negative_ttl = negative_ttl
        if protocol_rname is not None:
            self.protocol_rname = protocol_rname
        if refresh is not None:
            self.refresh = refresh
        if retry is not None:
            self.retry = retry
        if rname is not None:
            self.rname = rname

    @property
    def default_ttl(self):
        """Gets the default_ttl of this ConfigZoneAuthority.  # noqa: E501

        Optional. ZoneAuthority default ttl for resource records in zone (value in seconds). Defaults to 28800.  # noqa: E501

        :return: The default_ttl of this ConfigZoneAuthority.  # noqa: E501
        :rtype: int
        """
        return self._default_ttl

    @default_ttl.setter
    def default_ttl(self, default_ttl):
        """Sets the default_ttl of this ConfigZoneAuthority.

        Optional. ZoneAuthority default ttl for resource records in zone (value in seconds). Defaults to 28800.  # noqa: E501

        :param default_ttl: The default_ttl of this ConfigZoneAuthority.  # noqa: E501
        :type: int
        """

        self._default_ttl = default_ttl

    @property
    def expire(self):
        """Gets the expire of this ConfigZoneAuthority.  # noqa: E501

        Optional. ZoneAuthority expire time in seconds. Defaults to 2419200.  # noqa: E501

        :return: The expire of this ConfigZoneAuthority.  # noqa: E501
        :rtype: int
        """
        return self._expire

    @expire.setter
    def expire(self, expire):
        """Sets the expire of this ConfigZoneAuthority.

        Optional. ZoneAuthority expire time in seconds. Defaults to 2419200.  # noqa: E501

        :param expire: The expire of this ConfigZoneAuthority.  # noqa: E501
        :type: int
        """

        self._expire = expire

    @property
    def negative_ttl(self):
        """Gets the negative_ttl of this ConfigZoneAuthority.  # noqa: E501

        Optional. ZoneAuthority negative caching (minimum) ttl in seconds. Defaults to 900.  # noqa: E501

        :return: The negative_ttl of this ConfigZoneAuthority.  # noqa: E501
        :rtype: int
        """
        return self._negative_ttl

    @negative_ttl.setter
    def negative_ttl(self, negative_ttl):
        """Sets the negative_ttl of this ConfigZoneAuthority.

        Optional. ZoneAuthority negative caching (minimum) ttl in seconds. Defaults to 900.  # noqa: E501

        :param negative_ttl: The negative_ttl of this ConfigZoneAuthority.  # noqa: E501
        :type: int
        """

        self._negative_ttl = negative_ttl

    @property
    def protocol_rname(self):
        """Gets the protocol_rname of this ConfigZoneAuthority.  # noqa: E501

        Optional. A domain name which specifies the mailbox of the person responsible for this zone. Read-only Defaults to empty.  # noqa: E501

        :return: The protocol_rname of this ConfigZoneAuthority.  # noqa: E501
        :rtype: str
        """
        return self._protocol_rname

    @protocol_rname.setter
    def protocol_rname(self, protocol_rname):
        """Sets the protocol_rname of this ConfigZoneAuthority.

        Optional. A domain name which specifies the mailbox of the person responsible for this zone. Read-only Defaults to empty.  # noqa: E501

        :param protocol_rname: The protocol_rname of this ConfigZoneAuthority.  # noqa: E501
        :type: str
        """

        self._protocol_rname = protocol_rname

    @property
    def refresh(self):
        """Gets the refresh of this ConfigZoneAuthority.  # noqa: E501

        Optional. ZoneAuthority refresh. Defaults to 10800.  # noqa: E501

        :return: The refresh of this ConfigZoneAuthority.  # noqa: E501
        :rtype: int
        """
        return self._refresh

    @refresh.setter
    def refresh(self, refresh):
        """Sets the refresh of this ConfigZoneAuthority.

        Optional. ZoneAuthority refresh. Defaults to 10800.  # noqa: E501

        :param refresh: The refresh of this ConfigZoneAuthority.  # noqa: E501
        :type: int
        """

        self._refresh = refresh

    @property
    def retry(self):
        """Gets the retry of this ConfigZoneAuthority.  # noqa: E501

        Optional. ZoneAuthority retry. Defaults to 3600.  # noqa: E501

        :return: The retry of this ConfigZoneAuthority.  # noqa: E501
        :rtype: int
        """
        return self._retry

    @retry.setter
    def retry(self, retry):
        """Sets the retry of this ConfigZoneAuthority.

        Optional. ZoneAuthority retry. Defaults to 3600.  # noqa: E501

        :param retry: The retry of this ConfigZoneAuthority.  # noqa: E501
        :type: int
        """

        self._retry = retry

    @property
    def rname(self):
        """Gets the rname of this ConfigZoneAuthority.  # noqa: E501

        Optional. ZoneAuthority rname. Defaults to empty.  # noqa: E501

        :return: The rname of this ConfigZoneAuthority.  # noqa: E501
        :rtype: str
        """
        return self._rname

    @rname.setter
    def rname(self, rname):
        """Sets the rname of this ConfigZoneAuthority.

        Optional. ZoneAuthority rname. Defaults to empty.  # noqa: E501

        :param rname: The rname of this ConfigZoneAuthority.  # noqa: E501
        :type: str
        """

        self._rname = rname

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigZoneAuthority, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigZoneAuthority):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
