# coding: utf-8

"""
    DNS Configuration API

    The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.    # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConfigACLItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access': 'str',
        'acl': 'str',
        'address': 'str',
        'element': 'str'
    }

    attribute_map = {
        'access': 'access',
        'acl': 'acl',
        'address': 'address',
        'element': 'element'
    }

    def __init__(self, access=None, acl=None, address=None, element=None):  # noqa: E501
        """ConfigACLItem - a model defined in Swagger"""  # noqa: E501

        self._access = None
        self._acl = None
        self._address = None
        self._element = None
        self.discriminator = None

        self.access = access
        if acl is not None:
            self.acl = acl
        if address is not None:
            self.address = address
        self.element = element

    @property
    def access(self):
        """Gets the access of this ConfigACLItem.  # noqa: E501

        Required. Access permission for element. Allowed values: - allow - deny  # noqa: E501

        :return: The access of this ConfigACLItem.  # noqa: E501
        :rtype: str
        """
        return self._access

    @access.setter
    def access(self, access):
        """Sets the access of this ConfigACLItem.

        Required. Access permission for element. Allowed values: - allow - deny  # noqa: E501

        :param access: The access of this ConfigACLItem.  # noqa: E501
        :type: str
        """
        if access is None:
            raise ValueError("Invalid value for `access`, must not be `None`")  # noqa: E501

        self._access = access

    @property
    def acl(self):
        """Gets the acl of this ConfigACLItem.  # noqa: E501

        The resource identifier.  # noqa: E501

        :return: The acl of this ConfigACLItem.  # noqa: E501
        :rtype: str
        """
        return self._acl

    @acl.setter
    def acl(self, acl):
        """Sets the acl of this ConfigACLItem.

        The resource identifier.  # noqa: E501

        :param acl: The acl of this ConfigACLItem.  # noqa: E501
        :type: str
        """

        self._acl = acl

    @property
    def address(self):
        """Gets the address of this ConfigACLItem.  # noqa: E501

        Optional. Data for ip element. Must be empty if element is not \"ip\".  # noqa: E501

        :return: The address of this ConfigACLItem.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this ConfigACLItem.

        Optional. Data for ip element. Must be empty if element is not \"ip\".  # noqa: E501

        :param address: The address of this ConfigACLItem.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def element(self):
        """Gets the element of this ConfigACLItem.  # noqa: E501

        Required. Type of element. Allowed values: - any - ip - acl  # noqa: E501

        :return: The element of this ConfigACLItem.  # noqa: E501
        :rtype: str
        """
        return self._element

    @element.setter
    def element(self, element):
        """Sets the element of this ConfigACLItem.

        Required. Type of element. Allowed values: - any - ip - acl  # noqa: E501

        :param element: The element of this ConfigACLItem.  # noqa: E501
        :type: str
        """
        if element is None:
            raise ValueError("Invalid value for `element`, must not be `None`")  # noqa: E501

        self._element = element

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigACLItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigACLItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
