# coding: utf-8

"""
    DNS Configuration API

    The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.    # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConfigDisplayView(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'comment': 'str',
        'name': 'str',
        'view': 'str'
    }

    attribute_map = {
        'comment': 'comment',
        'name': 'name',
        'view': 'view'
    }

    def __init__(self, comment=None, name=None, view=None):  # noqa: E501
        """ConfigDisplayView - a model defined in Swagger"""  # noqa: E501

        self._comment = None
        self._name = None
        self._view = None
        self.discriminator = None

        if comment is not None:
            self.comment = comment
        if name is not None:
            self.name = name
        if view is not None:
            self.view = view

    @property
    def comment(self):
        """Gets the comment of this ConfigDisplayView.  # noqa: E501

        Read-only. DNS view description.  # noqa: E501

        :return: The comment of this ConfigDisplayView.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this ConfigDisplayView.

        Read-only. DNS view description.  # noqa: E501

        :param comment: The comment of this ConfigDisplayView.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def name(self):
        """Gets the name of this ConfigDisplayView.  # noqa: E501

        Read-only. DNS view name.  # noqa: E501

        :return: The name of this ConfigDisplayView.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConfigDisplayView.

        Read-only. DNS view name.  # noqa: E501

        :param name: The name of this ConfigDisplayView.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def view(self):
        """Gets the view of this ConfigDisplayView.  # noqa: E501

        The resource identifier.  # noqa: E501

        :return: The view of this ConfigDisplayView.  # noqa: E501
        :rtype: str
        """
        return self._view

    @view.setter
    def view(self, view):
        """Sets the view of this ConfigDisplayView.

        The resource identifier.  # noqa: E501

        :param view: The view of this ConfigDisplayView.  # noqa: E501
        :type: str
        """

        self._view = view

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigDisplayView, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigDisplayView):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
